### ISSUE TITLE
Stopped working midnight 28th/29th jan

### ISSUE THREAD

**Issue by GSV3MiaC** [BJReplay/ha-solcast-solar#238]
As of 00:00 29th Jan the integration is producing a slew of errors and failing to generate most forecast sensors. I can only assume solcast must have changed the format. I updated to latest version 4 days ago. 

Sample log file attached. 

I do have 2 arrays defined for solcast, which may be unusual

![Image](https://github.com/user-attachments/assets/27024426-1cf8-4a49-a413-4b1329ad030a)

I am running 4.2.7 under HA 2025.1.3, on a headless pc running HA  OS

**Comment by GSV3MiaC** [comment]
Here is the detailed log for just one of the many errors:

This error originated from a custom integration.

Logger: custom_components.solcast_solar.sensor
Source: custom_components/solcast_solar/sensor.py:467
integration: Solcast PV Forecast (documentation, issues)
First occurred: 12:00:00 AM (472 occurrences)
Last logged: 7:45:00 AM

Unable to get sensor value: 'pv_estimate': Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 465, in _handle_coordinator_update self._sensor_data = self._coordinator.get_sensor_value(self.entity_description.key) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 479, in get_sensor_value return self.__get_value[key][0]["method"]() ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 1912, in get_forecast_remaining_today self.__get_forecast_pv_remaining( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ start_utc, ^^^^^^^^^^ ...<2 lines>... forecast_confidence=forecast_confidence, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ), ^ File "/config/custom_components/solcast_solar/solcastapi.py", line 2208, in __get_forecast_pv_remaining result = self.__get_remaining(site, forecast_confidence, (start_utc - day_start).total_seconds()) File "/config/custom_components/solcast_solar/solcastapi.py", line 2171, in __get_remaining return self._forecasts_remaining["all" if site is None else site][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ self._use_forecast_confidence if forecast_confidence is None else forecast_confidence ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ][int(n_min / 300)] ^ KeyError: 'pv_estimate'
Unable to get sensor value: 'pv_estimate': Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 465, in _handle_coordinator_update self._sensor_data = self._coordinator.get_sensor_value(self.entity_description.key) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 478, in get_sensor_value return self.__get_value[key][0]["method"](self.__get_value[key][0].get("value", 0)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 1824, in get_forecast_custom_hours * self.__get_forecast_pv_remaining( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ start_utc, ^^^^^^^^^^ ...<2 lines>... forecast_confidence=forecast_confidence, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/config/custom_components/solcast_solar/solcastapi.py", line 2208, in __get_forecast_pv_remaining result = self.__get_remaining(site, forecast_confidence, (start_utc - day_start).total_seconds()) File "/config/custom_components/solcast_solar/solcastapi.py", line 2171, in __get_remaining return self._forecasts_remaining["all" if site is None else site][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ self._use_forecast_confidence if forecast_confidence is None else forecast_confidence ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ][int(n_min / 300)] ^ KeyError: 'pv_estimate'
Unable to get sensor value: 'int' object is not subscriptable: Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 465, in _handle_coordinator_update self._sensor_data = self._coordinator.get_sensor_value(self.entity_description.key) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 478, in get_sensor_value return self.__get_value[key][0]["method"](self.__get_value[key][0].get("value", 0)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 1873, in get_peak_power_day return 0 if result is None else round(1000 * result[forecast_confidence]) ~~~~~~^^^^^^^^^^^^^^^^^^^^^ TypeError: 'int' object is not subscriptable
Unable to get sensor value: 'int' object is not subscriptable: Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 465, in _handle_coordinator_update self._sensor_data = self._coordinator.get_sensor_value(self.entity_description.key) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 478, in get_sensor_value return self.__get_value[key][0]["method"](self.__get_value[key][0].get("value", 0)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 1895, in get_peak_time_day return result if result is None else result["period_start"] ~~~~~~^^^^^^^^^^^^^^^^ TypeError: 'int' object is not subscriptable
Unable to get sensor value: 'pv_estimate': Traceback (most recent call last): File "/config/custom_components/solcast_solar/sensor.py", line 465, in _handle_coordinator_update self._sensor_data = self._coordinator.get_sensor_value(self.entity_description.key) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/coordinator.py", line 478, in get_sensor_value return self.__get_value[key][0]["method"](self.__get_value[key][0].get("value", 0)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 1850, in get_power_n_minutes return round(1000 * self.__get_forecast_pv_moment(time_utc, site=site, forecast_confidence=forecast_confidence)) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/solcast_solar/solcastapi.py", line 2328, in __get_forecast_pv_moment result = self.__get_moment(site, forecast_confidence, (time_utc - day_start).total_seconds()) File "/config/custom_components/solcast_solar/solcastapi.py", line 2151, in __get_moment return self._forecasts_moment["all" if site is None else site][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ self._use_forecast_confidence if forecast_confidence is None else forecast_confidence ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ][int(n_min / 300)] ^ KeyError: 'pv_estimate'

**Comment by gcoan** [comment]
My Solcast integration is working fine, also with two arrays so I don't think its a problem with the integration.

Try shutting down and restarting Home Assistant

```
2025-01-29 00:00:00.211 INFO (MainThread) [custom_components.solcast_solar.coordinator] Auto forecast updates for today at 07:43:47, 09:58:56, 12:14:06, 14:29:16
2025-01-29 01:05:00.494 INFO (MainThread) [custom_components.solcast_solar] Forced update: Fetching forecast
2025-01-29 01:05:00.496 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site bc31-4d4c-xxxx-xxxx
2025-01-29 01:05:02.413 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site 23bb-0216-xxxx-xxxx
2025-01-29 01:05:04.985 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update completed successfully, next auto update at 2025-01-29 07:43:47
2025-01-29 02:31:27.453 ERROR (MainThread) [homeassistant.components.shelly] Error fetching Shelly-EM1 data: Error fetching data: DeviceConnectionTimeoutError(TimeoutError())
2025-01-29 05:12:02.739 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Internal error encountered. This message is generated externally to Home Assistant.
2025-01-29 07:43:47.454 INFO (MainThread) [custom_components.solcast_solar.coordinator] Auto update forecast
2025-01-29 07:43:47.455 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site bc31-4d4c-xxxx-xxxx
2025-01-29 07:43:48.676 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Getting forecast update for site 23bb-0216-xxxx-xxxx
2025-01-29 07:43:51.636 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update completed successfully, next auto update at 09:58:56
```

**Comment by GSV3MiaC** [comment]
I restarted ha and forced an update to a sensor, and am still getting errotlrs like:

This error originated from a custom integration.

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:2243
integration: Solcast PV Forecast (documentation, issues)
First occurred: 8:02:53 AM (12 occurrences)
Last logged: 8:10:00 AM

Exception in __get_forecast_pv_remaining(): 'pv_estimate': Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 2208, in __get_forecast_pv_remaining result = self.__get_remaining(site, forecast_confidence, (start_utc - day_start).total_seconds()) File "/config/custom_components/solcast_solar/solcastapi.py", line 2171, in __get_remaining return self._forecasts_remaining["all" if site is None else site][ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ self._use_forecast_confidence if forecast_confidence is None else forecast_confidence ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ][int(n_min / 300)] ^ KeyError: 'pv_estimate'
Exception in __get_forecast_pv_remaining(): '4b86-35cf-88bb-ed61': Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 2208, in __get_forecast_pv_remaining result = self.__get_remaining(site, forecast_confidence, (start_utc - day_start).total_seconds()) File "/config/custom_components/solcast_solar/solcastapi.py", line 2171, in __get_remaining return self._forecasts_remaining["all" if site is None else site][ ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: '4b86-35cf-88bb-ed61'

**Comment by autoSteve** [comment]
Those log entries are a symptom, not the root, and just noise. And they are highly un-readable (please use back-ticks ``` to enclose posted logs, @GSV3MiaC).

This is a symptom of remaining and momentary splines not being available for a given pv_estimate type (10/50/90).

I believe this emanates from a bug in v4.2.7 where logs explode like this after messing with attribute breakdown options. pv_estimate50 I believe.

It is highly likely that you changed options, or upgraded to this version (I have no context in this regard), and then midnight rolled over and the splines were recalculated.

Is this what happened? If so, turn the pv_estimate options back on for now and re-load the integration.

Fixed in v4.2.8 (coming).

**Comment by GSV3MiaC** [comment]
Thanks Steve, yes I upgraded to the 4.2.7 version 4 days ago. I changed no options, just forced to do various integration updates since BMW integration broke (by BMW). Will try what you suggest.

**Comment by GSV3MiaC** [comment]
Still does not produce most of the entities, with same log errors. Guess I have to wait for 4.2.8. The daily forecast for today is there, everything else (remaining, next 6 days, etc) comes up null.

**Comment by autoSteve** [comment]
This is most odd then.

It is spline-related, so please post the log from the beginning of start (in back-ticks ```) up to where the log spews. Debug logging enabled would also be of benefit (https://github.com/BJReplay/ha-solcast-solar/discussions/38#discussioncomment-9792389).

Please also post your options set, ensuring your API key is not in the snip.

**Comment by autoSteve** [comment]
(Or simply attach the log. At debug level the set options are logged, so if it's simpler just attach a debug log alone.)

**Comment by GSV3MiaC** [comment]
Here is the last part of the log, hope it contains all you need.

[home-assistant_2025-01-29T09-05-28.901Z.log](https://github.com/user-attachments/files/18585068/home-assistant_2025-01-29T09-05-28.901Z.log)

and here is options

![Image](https://github.com/user-attachments/assets/eaebb5f9-e7a7-45b3-8580-3bc158d4ca19)

**Comment by GSV3MiaC** [comment]
These are the sensors it can/can't get:

![Image](https://github.com/user-attachments/assets/a6e42ae1-9bad-48e4-90e6-42a8d4a4e1c9)

**Comment by autoSteve** [comment]
Enable all of these. Well, try and just ENABLE estimate 50 first, not disable. That is the cause of the log explosion.

Then reload integration.

<img width="345" alt="Image" src="https://github.com/user-attachments/assets/db74cb59-d76d-402b-9079-956fd37d1c2e" />

**Comment by GSV3MiaC** [comment]
I had already tried changing them both ways, no joy. I just ticked 50, and reloaded, and this is the log:

![Image](https://github.com/user-attachments/assets/b694b631-86a8-44f7-90e0-ca27228f92e9)

Maybe is easier to delete the integration completely and reload from scratch? I have no idea what version I was at before I upgraded.

**Comment by autoSteve** [comment]
You could try turning all options on except the site breakdown, (and of course don't tick the modify dampening dactors). This is the default options settings.

Rather than scortched-earth remove/re-install, I would rather get to the bottom of this to understand whether it is a known issue with 4.2.7.

**Comment by autoSteve** [comment]
From your attached log the logged issue is now with `pv_estimate10`, and not `pv_estimate`. This directly speaks to the bug in 4.2.7.

Enable the options as I asked, then re-load the integration.

**Comment by GSV3MiaC** [comment]
OK here is the current options (less api key):

![Image](https://github.com/user-attachments/assets/f429067e-6d3c-4052-bdb6-0d5d014c8ee7)

reloaded integration asked for an update of entities, got same errors in log and missing entity data.

I see in the ha /config folder there is a solcast.json (and a couple of others) which have not been up[dated since the version change on 22/Jan .. should those be rewritten? The solcast-sites.json was rewritten today.

**Comment by autoSteve** [comment]
-sites.json gets written every startup.
-usage gets written on every forecast update.
solcast.json gets written on forecast update.
solcast-undampened gets written on forecast update.

I am out of ideas. What does "asked for an update of entities" mean? The integration will update all related entities on start...

**Comment by BJReplay** [comment]
> I think it is time to start afresh.

Can you please save a backup of the solcast*.* files?  We might get you to share them.

First, remove the integration.

If you updated from a very old version, it doesn't have much history, so the best bet is back up those files - so we can have a look, then delete them.

Then, with the files removed, add the integration again, and run through the basic configuration.  It should just work.

**Comment by timmo65** [comment]
Hello
I have done a fresh install of the latest version today and get this error after successful configuration. I have not used this integration before so started to look in here for issue. I have had an api for a couple of years and did a regen of this today but no good.   Not sure if this is the same issue as described here or a different one - or my error of course !   

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:1470
integration: Solcast PV Forecast ([documentation](https://github.com/BJReplay/ha-solcast-solar), [issues](https://github.com/BJReplay/ha-solcast-solar/issues))
First occurred: 1:04:27 PM (13 occurrences)
Last logged: 1:16:40 PM

Exception in load_saved_data(): Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 1364, in adds_moves_changes cache_sites = list(self._data["siteinfo"].keys()) ~~~~~~~~~~^^^^^^^^^^^^ KeyError: 'siteinfo' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/solcast_solar/solcastapi.py", line 1446, in load_saved_data await adds_moves_changes() File "/config/custom_components/solcast_solar/solcastapi.py", line 1383, in adds_moves_changes raise f"Exception while adding new sites: {e}" from e TypeError: exceptions must derive from BaseException

Thanks very much 
Martin

**Comment by autoSteve** [comment]
Totally different issue, @timmo65.

KeyError 'siteinfo' would indicate that you have come from a VERY old integration, probably from the early Oziee days or before.

This is not considered an "upgrade" in my opinion, however v4.2.8 when it is released will cope with this. I consider it a "migration" because the code is so far removed from that version that even Oziee did not code in a migration from v3 to v4.

My suggestion? Scorched earth re-installation. v3 did not retain history, so you are losing nothing if this is the case.

Delete everything `config/solcast*.json`, and then re-start the integration. This will use up two API calls per configured Solcast site, but should get you going.

If you want to double check before the "scorched earth" kill-it-with-fire approach, then post your `solcast.json` file from config here.

And welcome. This integration is much evolved.

**Comment by timmo65** [comment]
Hello and thanks for the welcome and super quick response. I had deleted the custom components folder but hadnt considered the json files. I removed those and it sprung into life. I must have meddled with this a couple of years ago and gave up on it - so now time to revisit. 
Thanks again.
Martin

**Comment by GSV3MiaC** [comment]
Steve, here are the solcast custom component files from backups. Not sure which one of the two sets was active when it last worked, I suspect maybe the antique 2024 version. Hopefully you can handle .zip 

[oldsolcast.zip](https://github.com/user-attachments/files/18589902/oldsolcast.zip)

files. let me know if you need more. I will also save the current solcast components folder before I slash and burn.

I suspect I may have similar problem to the one above - 'upgrading' via HACS some old installation which was not put there that way. Just took a week for the problem to work thru the caching and surface.

**Comment by BJReplay** [comment]
> oldsolcast.zip

Thanks, @GSV3MiaC - that's really useful.  It looks like you've gone from `"version": "v4.1.7"` to `"version": "v4.2.7"`, and your forecasts go back to 2024-07-15.  v4.1.7 was released in September, so that kind of implies that you were running an earlier version before 4.1.7.  The date on the files in the 2024 folder is 11 October, so that makes it look like that's when you updated to v4.1.7.

The big change in 4.1.8 was 

### Full spread of attributes breakdown by site

_Absolutely all sensor attributes may now be broken down by site, including the detailed half-hourly and hourly forecasts._

_For why? I dunno. They're there for the taking, and for you to decide what you want to do with the data. How about build an Apex chart representation of each site forecast? Or build an automated per-site dampening automation? Your install, your things. (And tell us if you can't do what you want because the data is missing. We may have missed exposing something.)_

`All attributes sent to Home Assistant may be configured in config options. You choose the clutter. Turn them on or off.`

_The big attributes, like per-site detailed forecasts are not sent to recorder, so your Home Assistant database size will not suffer even with everything turned on._

So you've upgraded from a non-attribute breakdown version to an attribute breakdown version - albeit one with a bug that has hit 2 other people (so we're not rushing the fix - but @autoSteve and I are both running the code that will be 4.2.8.  I still manage to break it every now and again, and Steve still manages to fix it.

solcast-undampened was created 2025-01-22T18:18:52+00:00 and indicates that at least one update worked but has a unix-epoch (1 Jan 1970) date for `last_attempt`.

It looks like it got your forecasts once around the 22nd, and that's why you had forecasts available until the 29th.

solcast.json indicates `"last_updated": "2025-01-22T18:14:03.800354+00:00", "version": 5, "last_attempt": "2025-01-22T18:14:03.800354+00:00", "auto_updated": false` which again corresponds with a single successful run on the 22nd.

Whereas solcast(1).json indicates: , `"last_updated": "2025-01-19T20:14:03.204608+00:00", "version": 4}` and runs up to the 26th.

So, it kind of feels like a v4 to v5 solcast.json format update gone wrong.

Having said that, it does look like the integration managed to migrate, because it has written new files.  If I was to guess - and that's all it is - you might have set some of the configuration options at the same time you set up the new version in such a way to allow it to upgrade, but not to then calculate splines (due to the bug in 4.2.7).  You didn't notice until the 29th because it had fetched forecasts.

@autoSteve I think this is the attributes issue already fixed, just with confusing timing.  It occurred around the 22nd, but wasn't noticed until the 29th when the forecasts ran out is my guess.

**Comment by BJReplay** [comment]
Pretty sure that this is: Fixed by #226

**Comment by autoSteve** [comment]
> it kind of feels like a v4 to v5 solcast.json format update gone wrong

That code is dumb as a bagful of hammers, so I'd think unlikely. I recently reviewed it because v4.2.7 -> v4.2.8+ transitions to v6 schema. I did not have to alter the upgrade sequence much, and the PyTest code tested fine for v4->v5. It still tests fine for v?->v5/v6.

My theory is that the integration was set in motion, performed one update because the cached data was desperately out of date (thanks, @gcoan for that feature), and then an automation to upgrade the forecasts was either disabled or non-existing. Auto-update is not mentioned in the .json files, and the default for an upgrade from an old version that did not do auto-update is auto-update _off_.

And then time passed. And the data available got less and less. And then, "surprise!" Log spew when data covering "today" ran out.

(Splined data is only built from a little over 24-hours worth of forecasts covering "today" and an hour into "tomoz".)

**Comment by BJReplay** [comment]
> and then an automation to upgrade the forecasts was either disabled or non-existing

> And then time passed. And the data available got less and less.

Ahh, that makes a lot of sense.

Would need lots of logs - and the stamina to want to review them for something that is known to be working again.

**Comment by autoSteve** [comment]
> And then, "surprise!" Log spew.

Which is actually a fascinating thought. We track the number of days ahead that have valid data available. At "~five days until the tank is empty" should the integration raise that a repair is required?

I do check for this situation now in v4.2.8, but the response is a rather benign only spew a few logs instead of filling the disk with them repeatedly every five minutes. But the user is unaware of this until they scratch their head wondering where solar forecasting went, and maybe have a gander at the logs.

**Comment by autoSteve** [comment]
> and the stamina to want to review

Pfft. That is what simulations are for. I can "run out of forecast data" in less than the time it takes to say "What the?"... 😂

**Comment by autoSteve** [comment]
This is more than possible, BTW, @BJReplay. A warning-level repair could be issued that points to the integration doco. Could be either fixed and dismissed by the user, or a repair action could constitute automatically turning on auto-update sunrise/sunset and restarting which would dismiss the repair automagically.

https://developers.home-assistant.io/docs/core/platform/repairs/

**Comment by GSV3MiaC** [comment]
Ah, when I used ha action 'update entity' after trying the fixes, maybe that just goes to look at the cached data (which is still not there?) rather than forcing a new api call? I assumed 'update 3 day forecast' and 'next hour' would invoke the whole 9 yards... Seems to do that for other integrations (bmw, tesla, etc).

By the way, thanks for all the efforts. Do you have a buy a beer link??

**Comment by autoSteve** [comment]
> Do you have a buy a beer link??

It's actually a pleasure. I want this to work for me so...

I do have a pat-me-on-the-bum link with a one-off or subscription on GitHub sponsors...

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/f2d6f33e-13b1-4081-bd14-17d9847bd0e6" />

**Comment by autoSteve** [comment]
> Ah, when I used ha action 'update entity' after trying the fixes, maybe that just goes to look at the cached data (which is still not there?) rather than forcing a new api call?

And correct. Issuing an action "Solcast PV Forecast: Update" would have revealed fruitful things. Until the forecasts ran out again, hence the need for an automation to call this, or simply enable auto-update and simplify things.

We don't get new data from Solcast on entity update because one prime reason. API calls are just way too scarce given the super-small daily quota of ten for new hobbyist users.

**Comment by autoSteve** [comment]
(Thank you, @GSV3MiaC for the couple of pots of ale.)

**Comment by GSV3MiaC** [comment]
Well the link was to the. Png image, but I founfld you anyway. 

⁣Rgds, Dave Storey​

**Comment by BJReplay** [comment]
> should the integration raise that a repair is required?

Good idea, if we know what the problem is.

> A warning-level repair could be issued that points to the integration doco.

Or...

> or a repair action could constitute automatically turning on auto-update sunrise/sunset and restarting which would dismiss the repair automagically.

Yeah, this seems like the go.  I won't attempt to mark it up in github, but a message along the lines of "No updates detected in the last five days - would you like to enable automatic updates?  Choose Yes to enable automatic updates, Dismiss to dismiss this message and not enable updates".

Fire after 3 days as part of the stale check - so if they dismiss after the first warning, they get notifications for the next three days before it explodes.

**Comment by GSV3MiaC** [comment]
Ah so 'update entity day 3 forecast' is basically a nop, unless the date has changed. 
I am an antique user, got 50 api calls. 🙂

⁣Rgds, Dave Storey​

**Comment by autoSteve** [comment]
> Yeah, this seems like the go.

I was lookin' to do something this evening. It's either this or Rambo, pt 4.

Rambo is actually winning for the time being, as one cannot get enough of Stallone's, "Mmmf, ya know whaaaa? Heard he bought it back in Nammm, but sclywg sez hm gfmmm bhurff and ta-da, a fkn ROCKET!" He's so articulate.

**Comment by autoSteve** [comment]
Super disappointed no [Andy Vajna](https://variety.com/2019/film/global/andy-vajna-dead-dies-rambo-producer-1203113066/) producing "Rambo: Last Blood". (Vagna. Tee-hee.)

He died in 2019, the same year this last missive was released upon the world, only receiving a critics "meh" and barely a cap dothing to the closure. _"It is the streak of flabby sentimental self-importance that makes Rambo: Last Blood unwatchable."_

Righto. I think you kind of missed the point that Rambo is now an old bastard who fought like a man possessed for one last time for a real and personal "human" reason, not a senseless war and now done has no fight left in him, and shall not fight again. Kind of symbolically going down with the Vagna trilogy ship.

Ende.

I thought it was a perfectly unwatchable book-end. It never wanted writing, but it deffo wanted watching.

**Comment by BJReplay** [comment]
> I am an antique user, got 50 api calls. 🙂

So am I - but I only use 20 of them.  30 are for testing this integration 🤣

> Ah so 'update entity day 3 forecast' is basically a nop, unless the date has changed.

If you want to update forecasts, you need to call the action force_update_forecasts.  It can be done through developer tools, or the simplest automation which you run when you want to update them:

``` yaml
alias: Solcast Force Update
description: Solcast Force Update
mode: single
triggers: []
conditions: []
actions:
  - action: solcast_solar.force_update_forecasts
    data: {}
```

This will cause the integration to request new data from Solcast (and, providing that Solcast is playing nice and doesn't 429 and time out or refuse to serve you), will fetch that data, and update all the sensors.

![Image](https://github.com/user-attachments/assets/02cbef73-6358-460d-9dd8-99082615c7b9)

After calling the automation:

![Image](https://github.com/user-attachments/assets/0871efd2-249f-466a-a7ed-c33c0c9006ac)

**Comment by GSV3MiaC** [comment]
If it is 'going to explode' , just do an update whether the user wants one or not. You are just using one api call, and avoiding a major support furore. I mean one api call, come on, not like you are wiping their hard drive, or abducting their wife. 🙂

**Comment by autoSteve** [comment]
> I mean one api call, come on

Auto-update by stealth. A possibility, although not without its weaknesses, too.

A networking issue that prevents forecast updates over a period of time will also result in the days ahead dwindling.

* Is auto-update enabled or disabled?
* Does an automation exist?
* Is that automation enabled?
* Does that automation have a YAML issue?
* Has a network change been done?
* Does the Docker container running HA have an outbound network forwarding configuration issue?
* Has the broadband bill been paid?
* ...

**Comment by GSV3MiaC** [comment]
Yes it can still fail, and then you crater as before (but most of those failures won't even USE the one api call, because you get nowhere near the website)

**Comment by BJReplay** [comment]
Simple is best, here:

1. Do we want to automate and create maintenance burden for what is demonstrably a rare event?
2. If so, what is the simplest way to fix the problem that will work in the majority of cases with the least risk?

As the repo owner, and having been in this (software) game for a while, this looks like a scale perspective issue:

- @GSV3MiaC has hit a problem, and is rightly concerned with fixing it, and helping avoid others hitting the same problem.  From your perspective, this looks like a big deal - it has happened 100% of times you've upgraded recently.
- From our perspective, this is an edge case that has happened once to our knowledge in over 7000 installs - 0.014% of cases.
- Can we make it go away (or reduce by an order of magnitude so that it only occurs in one in 70,000 installs)?  Well, to do that, we'd need to increase our install base by a factor of ten **and** and make the code 10 times more reliable at the same time.
- If it turns out that there is an easy, low risk fix to make this problem go away, we (@autoSteve 🤣) will.
- But if not, we'll probably solve it with notes in the documentation - much less maintenance burden.

**Comment by autoSteve** [comment]
Simple is best @BJReplay. Read the doco is good, but being alerted when the future forecasts are starting to run out is a step better, and a low risk change.

I shall also attempt to add a link in the repair dialogue to the doco...

**Comment by autoSteve** [comment]
Pressing "Learn more" takes the user to the GitHub README.md section regarding updating forecasts.

<img width="1105" alt="Image" src="https://github.com/user-attachments/assets/60640348-9254-47d1-9a27-89ef266c2dc5" />

**Comment by GSV3MiaC** [comment]
I was calling manual update about once an hour iirc. The updated integration had the auto update box checked (see screenshot from 2 data ago) , but seems like (even after ha restart) that was not happening, and I guess the updated integration was not accepting the previous hourly calls?

After slash and burn the auto update is working fine as far as I can tell, and yes, it is bleating about manual update calls which I had failed to disable.

**Comment by autoSteve** [comment]
Fascinating, @GSV3MiaC. I had "tunnel vision" for the attribute options, and did not spot the auto-update setting change.

Changing the setting for auto-update will result in an integration re-start. That it did not auto-update is disturbing. And way-out-of-date forecast should also result in an immediate fetch on load, but sadly I could not see if that had attempted because not in log.

The earlier zipped log was partial, and not from the start of HA load. What were the actual settings at that time? Not sure because almost certainly not at `DEBUG` level, plus not from IPL.

I got nothing but the currently committed Band-aid.

**Comment by autoSteve** [comment]
(Soz. IPL = Initial Programme Load. IBM speak. Soz. I hate acronyms, yet I used an acronym... 🤦🏻)

**Comment by autoSteve** [comment]
@BJReplay, statistics be damned, we may hit this one again given the latest from Dave. Hope not 🤞, but there would appear to be an elusive hole that wants plugging given he/they/it (can't be sure of pronouns these days, @GSV3MiaC 😂) switched to auto-updates. This should have got things back on the straight and level, and yet... Yeah, nah. Boom.

**Comment by autoSteve** [comment]
(Then again, maybe not enough time had elapsed to allow an auto-update to occur. This was all in the same evening I think. Any configured automation doing a simple "update" would have been refused because auto-update set, requiring a "force update" instead...)

**Comment by autoSteve** [comment]
(But then, ignore me. On re-start an "ancient" update check would occur [thanks to @gcoan], and an update should be forced. So again, back to I got nothin'. Unless that update was blocked in v4.2.7, which is plausible.)

**Comment by BJReplay** [comment]
> this one again given the latest from Dave.

Yeah, it is interesting. Replying from my phone, but, from memory I thought auto-update was off from the zipped configs shared. Not gonna attempt to open zip the Json from phone, but even if I were to, it won't recreate the history or sequence of events.

At least one (and possibly at most one) fetch was done. solcast.json and solcast-usage.json were written.

And I have been typing wss so much today that the phone corrected was to wss.

**Comment by GSV3MiaC** [comment]
Sundry replies ..

Dave = GSV3MiaC (GSV 3 Minds in a Can .. you have to be an Iain M Banks fan)

I updated via HACS from an ancient version, which I may not have fully cleaned up. I did not change any config options. I may have logs back that far, but not debug log. Should have defaulted to 'auto' but apparently something was never set up because ..

I continued to run hourly " Perform action 'Solcast PV Forecast: Update' " automation, and got no bleating about it being configured for auto (though it did that after I slashed and burned). It obviously was NOT going getting the data, though I don't think I have api usage data back that far to see.  Nor was the auto update getting any, and I also had several restarts over the period iirc.

the log shows lots of 'gee the data is ancient' complaints, right before it then spewed the spline errors. The HA config shows that the .json files were not apparently updated (though whether that happens early in the fetch I don't know .. I would suspect those would be written early??)

Let me know if I can did out any more. I guess the logs may also be in the backups which I still have, but debug won't be on.

**Comment by autoSteve** [comment]
Two distinct repair flows now, @BJReplay...

First if auto-update is already enabled and forecast data is running out:

<img width="576" alt="image" src="https://github.com/user-attachments/assets/9d0753b7-9e4a-4249-b203-a633405566c5" />

Second if updates are manual and forecast data is running out:

<img width="609" alt="image" src="https://github.com/user-attachments/assets/5f3149f1-c46f-4575-ac2f-2674fc4113de" />

**Comment by BJReplay** [comment]
That is brilliant.

I have just spent 4 hours as an electrician's apprentice - 7.3kW charger installed. And water skiing this morning. I am stuffed.

**Comment by autoSteve** [comment]
> I have just spent 4 hours as an electrician's apprentice

Usually involves getting sent under the floorboards with the white tail spiders or into the roof cavity with mice, rats and possum piss. Hope not. 😂

Rest. Beer. Revive.

**Comment by BJReplay** [comment]
> roof cavity

And some work on a ladder with a yellow-tongue.

Really neat install, impressed with the sparky.

Charger is on OCPP, automations are drafted for charge at full noise from 11am to 1:55pm, and excess solar the rest of the time.  Yet to be tested on real hardware, but seemed to work on the simulator.
